model = ttk.Combobox(frame,width=20,font=("Segoe UI","14"),values=models)
    model.grid(row=1,column=1,padx=10,pady=5)
    model.bind('<KeyRelease>',searchModel)
    finish = ttk.Combobox(frame,width=20,font=("Segoe UI","14"),values=finishes)
    finish.grid(row=2,column=1,padx=10,pady=5)
    finish.bind('<KeyRelease>',searchFinish)
    size = ttk.Combobox(frame,width=20,font=("Segoe UI","14"),values=sizes)
    size.grid(row=3,column=1,padx=10,pady=5)
    size.bind('<KeyRelease>',searchSize)
    quantity = Entry(frame,width=22,font=("Segoe UI","14"))
    quantity.grid(row=4,column=1,padx=10,pady=5)
    dateoforder =Entry(frame,width=22,font=("Segoe UI","14"))
    dateoforder.insert(0, today[:11])
    dateoforder.grid(row=5,column=1,padx=10,pady=5) 